ci_pipeline: 
       on:
        push:
        branches:
          - main
       
        steps:
          - name: Execute script
            env:
              DBNAME: ${{ secrets.DBNAME }}
              SAYAYIN: ${{ secrets.CYBERIA }}
              LASTNAME: ${{ secrets.DANIEL }}  
              TRUENAME: ${{ env.DANIEL }}  
              YESNAME: ${{ vars.DANIEL }}  
              SINAME: VEGETA
