name: Set Environment Variable in cPanel
on:
  push:
    branches:
      - main
jobs:
  set-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variable in cPanel
        env:
          SITE_URL: 'https://adrian.starnetcomputers.us'
          API_TOKEN: ${{ secrets.CPANEL_TOKEN }}
          ENV_VAR_NAME: 'SAYAYIN'
          ENV_VAR_VALUE: ${{ secrets.CYBERIA }}
        run: |
          node set-var-env.js
