name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variable in cPanel
        uses: jazzdan/cpanel-setenv-action@v1
        with:
          domain: adrian.starnetcomputers.us
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          cpanel_password: ${{ secrets.CPANEL_PASSWORD }}
          name: SAYAYIN
          value: ${{ secrets.CYBERIA }}
          type: php
