name: Set Environment Variable in cPanel
on:
  push:
    branches:
      - main
jobs:
  set-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install cpanel-node
      - name: Set environment variable in cPanel
        env:
          SITE_URL: 'https://starnetcomputers.us'
          API_TOKEN: ${{ secrets.CPANEL_TOKEN }}
          USER: ${{ secrets.CPANEL_USERNAME }}
          PASS: ${{ secrets.CPANEL_PASSWORD }}
          VAR3: 'SAYAYIN'
          DBNAME: ${{ secrets.CYBERIA }}
        run: |
          node scripts/cpanelapi.js
