name: Set Environment Variable in cPanel
on:
  push:
    branches:
      - main
jobs:
  set-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variable in cPanel
        env:
          SITE_URL: 'https://starnetcomputers.us'
          API_TOKEN: ${{ secrets.CPANEL_TOKEN }}
          USER_NAME: ${{ secrets.CPANEL_USERNAME }}
          PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          ENV_VAR_NAME: 'SAYAYIN'
          ENV_VAR_VALUE: ${{ secrets.CYBERIA }}
        run: |
          php scripts/set-vars2.php
