name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variable in cPanel
        uses: jeracsi/cpanel-git-deploy@v1
        with:
          host: adrian.starnetcomputers.us
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          dir: /test/
          env: SAYAYIN=${{ secrets.CYBERIA }}
          
      - name: Deploy PHP Application
        run: |
          # Deploy your PHP application here
