name: Set Environment Variable in cPanel
on:
  push:
    branches:
      - main
jobs:
  set-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install axios
      - name: Set environment variable in cPanel
        env:
          SITE_URL: 'https://starnetcomputers.us'
          API_TOKEN: ${{ secrets.CPANEL_TOKEN }}
          USER_NAME: ${{ secrets.CPANEL_USERNAME }}
          PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          ENV_VAR_NAME: 'SAYAYIN'
          ENV_VAR_VALUE: ${{ secrets.CYBERIA }}
        run: |
          node scripts/set-vars.js $SITE_URL $API_TOKEN $ENV_VAR_NAME $ENV_VAR_VALUE
