ci_pipeline: 
       on:
        push:
        branches:
          - main
       
        steps:
          - name: Execute script
            env:
              DBNAME: ${{ secrets.DBNAME }}
       run: php index.php
       
