name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variable in cPanel
        uses: crazy-max/cpanel-git@v4
        with:
          host: example.com
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          dir: /path/to/app
          env: SAYAYIN=${{ secrets.CYBERIA }}
