name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
       DBNAME: ${{ secrets.DBNAME }}
       SAYAYIN: ${{ secrets.CYBERIA }}
       LASTNAME: ${{ secrets.DANIEL }}  
       TRUENAME: ${{ env.DANIEL }}  
       YESNAME: ${{ vars.DANIEL }}  
       SINAME: VEGETA
       run: |
          touch secrets.txt
          echo var2="$DBNAME" >> secrets.txt
          echo var3="$SAYAYIN" >> secrets.txt
          echo var4="$LASTNAME" >> secrets.txt
          echo var5="$TRUENAME" >> secrets.txt
          echo var6="$YESNAME" >> secrets.txt
          echo var7="$SINAME" >> secrets.txt
          ls ${{ github.workspace }}
      shell: bash
